name = "url-shortener"
main = "src/index.js"
compatibility_date = "2022-07-12"

account_id = "66b1a0ce80322d2eb8fc734d936a2f85"

workers_dev = false

routes = [
  "ehhh.eu.org/*",
  "api.ehhh.eu.org/*"
]

kv_namespaces = [
  { binding = "URLSHTNR", id = "599a80a92b7c4f6e8502dbb0b9d4f397" }
]

site = { bucket = "./public" }